import type { AlertStylesNames } from 'coengageui_core';

export const Alert: Record<AlertStylesNames, string> = {
  root: 'Root element',
  wrapper: 'Wraps body and icon',
  info__light: 'Light variant root element modifier',
  info__filled: 'Filed variant root element modifier',
  info__outline: 'Outline variant root element modifier',
  success__light: 'Light variant root element modifier',
  success__filled: 'Filed variant root element modifier',
  success__outline: 'Outline variant root element modifier',
  warning__light: 'Light variant root element modifier',
  warning__filled: 'Filed variant root element modifier',
  warning__outline: 'Outline variant root element modifier',
  danger__light: 'Light variant root element modifier',
  danger__filled: 'Filed variant root element modifier',
  danger__outline: 'Outline variant root element modifier',
  body: 'Body element, wraps title and message',
  title: 'Title element, contains label and icon',
  label: 'Title label',
  message: 'Alert message, defined by children',
  icon: 'Icon wrapper',
  closeButton: 'Close button, defined by withCloseButton prop',
  titlewrapper: '',
  header: '',
};
